apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform-app
  labels:
    app: devops-platform-app
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 180
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devops-platform-app
  template:
    metadata:
      labels:
        app: devops-platform-app
    spec:
      containers:
        - name: devops-platform-app
          image: __IMAGE__
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 3
