apiVersion: v1
kind: Service
metadata:
  name: devops-platform-app-service
spec:
  type: NodePort
  selector:
    app: devops-platform-app
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30080
